export const categories = [
  {
    title: 'Melhores jogos ao vivo',
    games: [
      { name: 'Football Studio', image: 'games/footbal-studio.png', stars: 5 },
      { name: 'Bac Bo', image: 'games/bac-bo.png', stars: 5 },
      { name: 'Immersive Roulette', image: 'games/roulette.png', stars: 3 },
      { name: 'Football Studio', image: 'games/footbal-studio.png', stars: 3 },
      { name: 'Bac Bo', image: 'games/bac-bo.png', stars: 3 },
      { name: 'Immersive Roulette', image: 'games/roulette.png', stars: 1 },
      { name: 'Football Studio', image: 'games/footbal-studio.png', stars: 1 },
      { name: 'Bac Bo', image: 'games/bac-bo.png', stars: 1 },
      { name: 'Immersive Roulette', image: 'games/roulette.png', stars: 1 },
    ],
  },
  {
    title: 'Roletas',
    games: [
      { name: 'Auto Mega Roulette', image: 'games/auto-mega-roulette.png', stars: 5 },
      { name: 'Immersive Roulette', image: 'games/immersive-roulette.png', stars: 5 },
      { name: 'Roulette', image: 'games/roulette.png', stars: 2 },
      { name: 'Auto Mega Roulette', image: 'games/auto-mega-roulette.png', stars: 2 },
      { name: 'Immersive Roulette', image: 'games/immersive-roulette.png', stars: 2 },
      { name: 'Roulette', image: 'games/roulette.png', stars: 2 },
      { name: 'Auto Mega Roulette', image: 'games/auto-mega-roulette.png', stars: 2 },
      { name: 'Immersive Roulette', image: 'games/immersive-roulette.png', stars: 2 },
      { name: 'Roulette', image: 'games/roulette.png', stars: 2 },
    ],
  },
  {
    title: 'Baccarat',
    games: [
      { name: 'Baccarat 8', image: 'games/baccarat-8.png', stars: 5 },
      { name: 'Baccarat A', image: 'games/baccarat-a.png', stars: 1 },
      { name: 'Baccarat Squeeze', image: 'games/baccarat-squeeze.png', stars: 1 },
      { name: 'Baccarat 8', image: 'games/baccarat-8.png', stars: 1 },
      { name: 'Baccarat A', image: 'games/baccarat-a.png', stars: 1 },
      { name: 'Baccarat Squeeze', image: 'games/baccarat-squeeze.png', stars: 1 },
      { name: 'Baccarat 8', image: 'games/baccarat-8.png', stars: 1 },
      { name: 'Baccarat A', image: 'games/baccarat-a.png', stars: 1 },
      { name: 'Baccarat Squeeze', image: 'games/baccarat-squeeze.png', stars: 1 },
    ],
  },
  {
    title: 'Blackjack',
    games: [
      { name: 'Azure Blackjack 1', image: 'games/azure-blackjack-1.png', stars: 5 },
      { name: 'Azure Blackjack 2', image: 'games/azure-blackjack-2.png', stars: 0 },
      { name: 'One Blackjack', image: 'games/one-blackjac.png', stars: 0 },
      { name: 'Azure Blackjack 1', image: 'games/azure-blackjack-1.png', stars: 0 },
      { name: 'Azure Blackjack 2', image: 'games/azure-blackjack-2.png', stars: 0 },
      { name: 'One Blackjack', image: 'games/one-blackjac.png', stars: 0 },
      { name: 'Azure Blackjack 1', image: 'games/azure-blackjack-1.png', stars: 0 },
      { name: 'Azure Blackjack 2', image: 'games/azure-blackjack-2.png', stars: 0 },
      { name: 'One Blackjack', image: 'games/one-blackjac.png', stars: 0 },
    ],
  },
  {
    title: 'Dados',
    games: [
      { name: 'Boom City', image: 'games/boom-city.png', stars: 5 },
      { name: 'SIC BAC', image: 'games/sic-bac.png', stars: 0 },
      { name: 'Mega SIC BO', image: 'games/mega-sic-bo.png', stars: 0 },
      { name: 'SIC BO', image: 'games/sic-bo.png', stars: 0 },
      { name: 'Boom City', image: 'games/boom-city.png', stars: 0 },
      { name: 'SIC BAC', image: 'games/sic-bac.png', stars: 0 },
      { name: 'Mega SIC BO', image: 'games/mega-sic-bo.png', stars: 0 },
      { name: 'SIC BO', image: 'games/sic-bo.png', stars: 0 },
      { name: 'Boom City', image: 'games/boom-city.png', stars: 0 },
      { name: 'SIC BAC', image: 'games/sic-bac.png', stars: 0 },
      { name: 'Mega SIC BO', image: 'games/mega-sic-bo.png', stars: 0 },
      { name: 'SIC BO', image: 'games/sic-bo.png', stars: 0 },
    ],
  },
];
